<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHomCv9g\srcTechnical_Apps_Optime_Backend_OptimeBackendKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHomCv9g/srcTechnical_Apps_Optime_Backend_OptimeBackendKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHomCv9g.legacy');

    return;
}

if (!\class_exists(srcTechnical_Apps_Optime_Backend_OptimeBackendKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerHomCv9g\srcTechnical_Apps_Optime_Backend_OptimeBackendKernelTestDebugContainer::class, srcTechnical_Apps_Optime_Backend_OptimeBackendKernelTestDebugContainer::class, false);
}

return new \ContainerHomCv9g\srcTechnical_Apps_Optime_Backend_OptimeBackendKernelTestDebugContainer([
    'container.build_hash' => 'HomCv9g',
    'container.build_id' => '754b05ae',
    'container.build_time' => 1607912076,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHomCv9g');
