services:
  _defaults:
    autoconfigure: true
    autowire: true

  Technical\Apps\Optime\Backend\Controller\:
    resource: '../src/Controller'
    tags: ['controller.service_arguments']

  Technical\Optime\:
    resource: '../../../../src/Optime'
