<?php

namespace ContainerHomCv9g;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthCheckGetControllerService extends srcTechnical_Apps_Optime_Backend_OptimeBackendKernelTestDebugContainer
{
    /**
     * Gets the public 'Technical\Apps\Optime\Backend\Controller\HealthCheck\HealthCheckGetController' shared autowired service.
     *
     * @return \Technical\Apps\Optime\Backend\Controller\HealthCheck\HealthCheckGetController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/HealthCheck/HealthCheckGetController.php';

        return $container->services['Technical\\Apps\\Optime\\Backend\\Controller\\HealthCheck\\HealthCheckGetController'] = new \Technical\Apps\Optime\Backend\Controller\HealthCheck\HealthCheckGetController();
    }
}
